include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_final_fields: true
