name: namer_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.13.1
  flutter_map_marker_cluster: ^0.4.0
  geojson: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/geojson_file_1.geojson
    - assets/geojson_file_2.geojson
    - assets/geojson_file_3.geojson
    - assets/geojson_file_4.geojson

