name: namer_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  flutter_map_geojson: ^0.4.0

  cupertino_icons: ^1.0.2






flutter:
  uses-material-design: true
  assets:
    - assets/geojson_file_1.geojson
dev_dependencies:
  flutter_lints: ^2.0.3


